### ISSUE TITLE
Installation and Configuration Troubles

### ISSUE THREAD

**Issue by im-nihal** [hossainchisty/FreshGerium-ERP-Platform#46]
Hi [hossainchisty](https://github.com/hossainchisty),

I hope this message finds you well. I'm reaching out because I've encountered some difficulties while trying to set up and run your Freshdesk-ERP-Platform repository. As a beginner in Django development, I found the lack of installation instructions and a requirements.txt file challenging, and I believe there might be a configuration issue.

**Here are the details of the problem:**

### Problem
When attempting to run python manage.py migrate, I encountered the following error:

```
(virt) x@gedion:~/Desktop/test/Freshdesk-ERP-Platform$ python manage.py migrate
Traceback (most recent call last):
  File "/home/gedion/Desktop/test/Freshdesk-ERP-Platform/manage.py", line 22, in <module>
    main()
  File "/home/gedion/Desktop/test/Freshdesk-ERP-Platform/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 117, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/gedion/Desktop/test/virt/lib/python3.11/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```
### Additional Challenges
- The repository lacks a `requirements.txt` file, making it unclear which dependencies are required.
- The project prompts me to turn off `DEBUG="False"` in development mode, even though it's already set to True.

### Request
As a beginner, I would greatly appreciate some guidance on the proper installation process and configuration settings. Additionally, it would be helpful if you could provide a clear set of instructions or a requirements.txt file to ensure that users can set up the project successfully.

### Request for Assistance

**_Kindly provide guidance on the following:_**

**1. Database Configuration:**

- What is the correct database engine to use for this project?
- How should I configure the DATABASES setting in settings.py?

**2. Installation Instructions:**

- Please outline the steps necessary to install and run the project successfully.
- If any specific dependencies are required, please list them.

**3. Debugging in Development Mode:**

- How can I resolve the issue of being prompted to turn off `DEBUG` mode in development?
Thank you for your time and support!

Additional Information:

I'm using Python version 3.11.
I'm working in a virtual environment named virt.
I'm attempting the installation on my machine running Ubuntu 23.04.
Please let me know if you need any further details from me.

Thank you!
Best regards,
[_its.nihal](https://github.com/its-nihal-patel)

**Comment by doraemonxxx** [comment]
LOL
